/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layouts/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layouts/AppHeader.vue')['default']
    AppLayout: typeof import('./src/components/layouts/AppLayout.vue')['default']
    AppSideBar: typeof import('./src/components/layouts/AppSideBar.vue')['default']
    BadgeTier: typeof import('./src/components/misc/BadgeTier.vue')['default']
    CreditUsageChart: typeof import('./src/components/dashboard/CreditUsageChart.vue')['default']
    PageHeader: typeof import('./src/components/common/PageHeader.vue')['default']
    PlanUpgradeModal: typeof import('./src/components/dashboard/PlanUpgradeModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_9a7706bbf8a67a23d140b48585a9f37c/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_9a7706bbf8a67a23d140b48585a9f37c/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_9a7706bbf8a67a23d140b48585a9f37c/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_9a7706bbf8a67a23d140b48585a9f37c/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UColorModeButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_9a7706bbf8a67a23d140b48585a9f37c/node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_9a7706bbf8a67a23d140b48585a9f37c/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_9a7706bbf8a67a23d140b48585a9f37c/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_9a7706bbf8a67a23d140b48585a9f37c/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    USelect: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_9a7706bbf8a67a23d140b48585a9f37c/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    UTable: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_9a7706bbf8a67a23d140b48585a9f37c/node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    UTooltip: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_9a7706bbf8a67a23d140b48585a9f37c/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
